language: go

go_import_path: github.com/lnhote/noah

go:
  - 1.10.x

addons:
   apt:
      packages: ['zlib1g-dev', 'libbz2-dev', 'liblz4-dev', 'libsnappy-dev', 'curl', 'libgflags-dev']

before_install:
#  - sudo apt-get install libgflags-dev
#  - sudo apt-get install libsnappy-dev
#  - sudo apt-get install zlib1g-dev
#  - sudo apt-get install libbz2-dev
#  - sudo apt-get install liblz4-dev
#  - sudo apt-get install libzstd-dev
  - git clone --depth=50 --branch=master https://github.com/facebook/rocksdb.git
  - cd rocksdb
  - make static_lib
  - curl https://glide.sh/get | sh
  - cd $HOME/gopath/src/github.com/lnhote/noah
  - glide install

script:
  - go test -tags="rocksdb" ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    - lnhote@gmail.com