language: go

go_import_path: github.com/lnhote/noah

go:
  - 1.10.x

before_install:
  - curl https://glide.sh/get | sh
  - glide install

script:
  - go test -tags="rocksdb" ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
