language: go

go:
  - 1.10.x
  - 1.x

before_install:
  - go get -v github.com/Masterminds/glide
  - glide i

script:
  - go test -tags="rocksdb" ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
