language: go

go_import_path: github.com/lnhote/noah

go:
  - 1.10.x

addons:
   apt:
      packages: ['zlib1g-dev', 'libbz2-dev', 'liblz4-dev', 'libsnappy-dev', 'curl', 'libgflags-dev']


before_install:
#  - sudo apt-get install libgflags-dev
#  - sudo apt-get install libsnappy-dev
#  - sudo apt-get install zlib1g-dev
#  - sudo apt-get install libbz2-dev
#  - sudo apt-get install liblz4-dev
#  - sudo apt-get install libzstd-dev
  - wget https://launchpad.net/ubuntu/+archive/primary/+files/libgflags2_2.0-1.1ubuntu1_amd64.deb
  - sudo dpkg -i libgflags2_2.0-1.1ubuntu1_amd64.deb
  - wget https://launchpad.net/ubuntu/+archive/primary/+files/libgflags-dev_2.0-1.1ubuntu1_amd64.deb
  - sudo dpkg -i libgflags-dev_2.0-1.1ubuntu1_amd64.deb
  - git clone --depth=50 --branch=master https://github.com/facebook/rocksdb.git /tmp/rocksdb
  - pushd /tmp/rocksdb
  - make shared_lib
  - sudo cp --preserve=links ./librocksdb.* /usr/lib/
  - sudo cp -r ./include/rocksdb/ /usr/include/
  - popd
  - curl https://glide.sh/get | sh
  - glide install

script:
  - go test -tags="rocksdb" ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    - lnhote@gmail.com