server_id: 1
leader_id: 5
cluster:
  - server_id: 1
    role: 0
    server_addr: 127.0.0.1:8881
  - server_id: 2
    role: 0
    server_addr: 127.0.0.1:8882
  - server_id: 3
    role: 0
    server_addr: 127.0.0.1:8883
  - server_id: 4
    role: 0
    server_addr: 127.0.0.1:8884
  - server_id: 5
    role: 2
    server_addr: 127.0.0.1:8885